### GET ALL
GET http://localhost:3000/players

### GET ONE BY ID
GET http://localhost:3000/players/1

### CREATE ONE
POST http://localhost:3000/players
Content-Type: application/json

{
	"name": "paolo",
	"password": "thebestone"
}

### UPDATE ONE
PATCH http://localhost:3000/players/1
Content-Type: application/json

{
	"name": "josé"
}

### DELETE ONE
DELETE http://localhost:3000/players/2
